# Generated by Django 4.2.10 on 2024-02-28 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_scrap', '0003_alter_news_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='id',
            field=models.SlugField(primary_key=True, serialize=False),
        ),
    ]
