# Generated by Django 4.2.10 on 2024-02-28 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_scrap', '0004_alter_news_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AlterField(
            model_name='news',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
