# Generated by Django 4.2.10 on 2024-02-28 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_scrap', '0005_news_slug_alter_news_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(default='', max_length=255),
        ),
    ]
