# Generated by Django 4.2.10 on 2024-02-28 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_scrap', '0006_alter_news_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sources',
            name='title',
            field=models.TextField(),
        ),
    ]
